config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'clients#index'
  resources :clients do
    collection do
      get 'search'
    end
    
    resources :calendars, only: [:index, :create, :show, :destroy]
  end
    resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  validates :plan, presence: true
  validates :date, presence: true

  belongs_to :client
  belongs_to :user
end

app/models/client.rb
class Client < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :from

  has_one_attached :image

  with_options presence: true do
    validates :name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
    validates :name_hiragana, format: { with: /\A[ぁ-んー－]+\z/ }
  end

  belongs_to :user
  has_many :calendars, dependent: :destroy

  def self.search(search)
    if search != ""
      Client.where('name LIKE(?)', "%#{search}%")
    else
      Client.all
    end
  end

end

app/models/from.rb
class From < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]
  include ActiveHash::Associations
  has_many :clients

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :clients

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :clients
  has_many :calendars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :move_to_index, except: [:edit, :new, :update, :destroy ]
  

  def index
    @calendar = Calendar.new
  end


  def create
    @calendar = Calendar.create(calendar_params)
    if @calendar.save
      redirect_to "/clients/#{@calendar.client.id}"
    end
  end

  def show
    @calendar = Calendar.find(params[:client_id])
  end

  def destroy
    @client = Client.find(params[:id])
    @calendar = Calendar.find(params[:client_id])
    if current_user.id == @client.user.id
      @calendar.destroy
      redirect_to "/clients/#{@calendar.client.id}"
    else
      redirect_to root_path
    end
  end

  private

  def calendar_params
    params.require(:calendar).permit(:date, :plan).merge(user_id: current_user.id, client_id: params[:client_id])
  end


  def move_to_index
    @client = Client.find(params[:client_id])
    if current_user.id != @client.user.id
      redirect_to root_path
    end
  end

  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_client, only: [:edit, :show, :destroy, :update]
  before_action :move_to_index, except: [:index, :new, :create, :search]
  
  def index
    @clients = Client.includes(:user).order("created_at DESC")
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    if @client.destroy
      redirect_to root_path
    end
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to client_path
    end
  end

  def show
    @calendar = @client.calendars
    redirect_to root_path if current_user.id != @client.user.id
  end

  def search
    @clients = Client.search(params[:keyword])
  end


  private

  def client_params
    params.require(:client).permit(:name, :name_hiragana, :birthday, :prefecture_id, :from_id, :corporation, :drink, :food, :cigarettes, :memo, :image).merge(user_id: current_user.id)
  end

  def set_client
    @client = Client.find(params[:id])
  end

  def move_to_index
    if current_user.id != @client.user.id
      redirect_to root_path
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = current_user.name
    @clients = current_user.clients
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/index.html.erb
<div class= calendar-body>
  <%= form_with model: @calendar, url: client_calendars_path, class: 'form' do |f| %>
    <%= f.label :日付を選択, class: 'lavel' %>
    <%= f.date_field :date, class: 'date-select' %>
    <%= f.label :予定を入力, class: 'lavel' %>
    <%= f.text_field :plan, class: 'text-input' %>
    <%= f.submit '追加', class: 'submit-button' %>
  <% end %>
</div>

app/views/clients/_client.html.erb
<%= f.text_field :name, placeholder: "名前" %>
      <%= f.text_field :name_hiragana, placeholder: "名前(かな)" %>
      <div class='form-text-wrap'>
        <label class="weight-bold-text">誕生日</label>
      </div>
      <div class='input-birth-wrap'>
        <%= raw sprintf(
                f.date_select(
                  :birthday,
                  class:'select-birth',
                  id:"birth-date",
                  use_month_numbers: true,
                  prompt:'--',
                  start_year: 1940,
                  end_year: (Time.now.year - 5),
                  date_separator: '%s'),
                "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      </div>
      <div class="weight-bold-text">住んでいるところ</div>
      <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box"}) %>
      <div class="weight-bold-text">出身地</div>
      <%= f.collection_select(:from_id, From.all, :id, :name, {}, {class:"select-box"}) %>
      <%= f.text_field :corporation, placeholder: "会社名" %>
      <%= f.text_field :drink, placeholder: "好きなお酒" %>
      <%= f.text_field :food, placeholder: "好きな食べ物" %>
      <%= f.text_field :cigarettes, placeholder: "タバコ" %>
      <%= f.text_area  :memo, placeholder: "メモ" %>
      <div class="img-upload">
      <div class="click-upload">
        <p>
          写真アップロード
        </p>
        <%= f.file_field :image, id:"#" %>
      </div>
    </div>

app/views/clients/_search.html.erb
<%= form_with(url: search_clients_path, local: true, method: :get, class: "search-form") do |f| %>
  <%= f.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= f.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @clients.each do |client| %>
    <div class="content_post">
      <%= image_tag client.image.variant(resize: '1000x1000'), class: 'client-image' if client.image.attached? %> 
      <span class="name">
        <a href="/clients/<%= client.id %>">
          <%= client.name %>
        </a>
      </span>
    </div>
  <% end %>
</div>

app/views/clients/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>顧客編集</h3>
    <%= form_with(model: @client, local: true) do |f| %>
      <%= render partial: "client", locals: { f: f } %>
      <%= f.submit "編集する" %>
    <% end %>
  </div>
</div>

app/views/clients/index.html.erb
<%= render partial: "search", locals: { f: @clients } %>

app/views/clients/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>顧客追加</h3>
    <%= form_with(model: @client, local: true) do |f| %>
      <%= render partial: "client", locals: { f: f } %>
      <%= f.submit "追加" %>
    <% end %>
  </div>
</div>

app/views/clients/search.html.erb
<%= render partial: "search", locals: { f: @clients } %>

app/views/clients/show.html.erb
<div class="item-show">
  <div class="item-box">
  <% if user_signed_in? && current_user.id == @client.user_id %>
    <div class="item-img-content">
      <%= image_tag @client.image ,class:"item-box-img" if @client.image.attached? %>
    </div>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">名前</th>
          <td class="detail-value"><%= @client.name %></td>
        </tr>
        <tr>
          <th class="detail-item">よみ</th>
          <td class="detail-value"><%= @client.name_hiragana %></td>
        </tr>
        <tr>
          <th class="detail-item">誕生日</th>
          <td class="detail-value"><%= @client.birthday %></td>
        </tr>
        <tr>
          <th class="detail-item">住んでいるところ</th>
          <td class="detail-value"><%= @client.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">出身地</th>
          <td class="detail-value"><%= @client.from.name %></td>
        </tr>
        <tr>
          <th class="detail-item">会社名</th>
          <td class="detail-value"><%= @client.corporation %></td>
        </tr>
        <tr>
          <th class="detail-item">好きなお酒</th>
          <td class="detail-value"><%= @client.drink %></td>
        </tr>
        <tr>
          <th class="detail-item">好きな食べ物</th>
          <td class="detail-value"><%= @client.food %></td>
        </tr>
        <tr>
          <th class="detail-item">タバコ</th>
          <td class="detail-value"><%= @client.cigarettes %></td>
        </tr>
        <tr>
          <th class="detail-item">メモ</th>
          <td class="detail-value"><%= @client.memo %></td>
        </tr>
        <div class='calendar'>
      <% @calendar.each do |c| %>
        <tr>
          <th class="detail-item"><%= c.date %></th>

          <td class="detail-value"><%= c.plan %>
            <div class="calendar-destroy-right">
              <%= link_to "削除", client_calendar_path(c.id), method: :delete, data: { confirm: '削除しますか？' }, class:"calendar-destroy" %>
            </div>
          </td>
        </tr>
      <% end %>
  </div>
      </tbody>
    </table>
    <%= link_to "予定追加ページへ", client_calendars_path(@client.id), method: :get, class: "calendar-btn" %>
    <%= link_to "顧客情報編集", edit_client_path(@client.id), method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "顧客削除", client_path(@client.id), method: :delete, data: { confirm: '削除しますか？' }, class:"item-destroy" %>
    <% end %>
  </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cmt35232</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href=".css" type="text/css">
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <header class="header">
      <div class="header__bar row">
        <span class="cmt-design">
          <h1 class="grid-6"><a href="/">CMT</a></h1>
        </span>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
          <div class="name-col">
            <span><%= current_user.name %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                <%= link_to "顧客追加", new_client_path, method: :get %>
              </li>
            </ul>
          </span>
          </div>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
  <p>
    Copyright CMT 2021.
  </p>
</footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @name %>の顧客一覧</p>
  <% @clients.each do |client| %>
    <div class="content_post">
      <%= image_tag client.image.variant(resize: '1000x1000'), class: 'client-image' if client.image.attached? %> 
      <span class="name">
        <a href="/clients/<%= client.user.id %>">
          <%= client.name %>
        </a>
      </span>
    </div>
  <% end %>
</div>